### PR TITLE
Encrypt file

### PR DESCRIPTION
**Pull request by vguzmanp**
Hi, I modified simple-crypt to encrypt a whole file, not just a string. It reads the file by chunks and reuses the same cipher object for each chunk.

I thought it could be useful, what do you think?

### CODE REVIEW

**Comment by andrewcooke** [comment]
hi.  thanks for this.  i was googling "simple-crypt" just the other day and there are a bunch of questions on stackoverflow with people having problems with encrypting files, so i was thinking of adding something.

however, i'm not sure if chunking is best.  i can see why you've done it that way - to avoid using too much memory.  but it means (i assume, haven't looked in detail at your code) that the file can be modified.  for example, someone could remove the middle of three chunks, and you, as the user, wouldn't know.  and yes, of course you can fix this by making things more complicated, but then things are complicated.  it would be better to find an existing standard for file encryption.  but that sounds like a lot of work :(

one alternative might be to encrypt as a stream.  but i think the hmac doesn't work in that case.  you would perhaps need to use two passes.  and what if someone found the intermediate pass?

so at the moment i think it might be best to treat a file as a single chunk.

but i haven't thought much about this.  i am thinking as i type.

so, again, thanks.  you've prompted me to do something about this.  but i am not sure what, yet.  i will look in detail at your patch and think some.  and i will leave this issue open.  when i have a clearer idea and free time (probably in a month or so) i will return to this and either merge this or write something similar.

cheers, andrew

**Comment by vguzmanp** [comment]
Yeah, I did this because I tried to encrypt a 1.5GB file and it kept raising MemoryError. The chunk size is set to 100MB right now.
The main change I did was extract the encrypt/decrypt code to a function receiving the cipher object, and call it with each chunk. I have no idea whether it makes it possible to modify the file :(

So, do as you see best, I'm glad I was at least a bit useful :)

**Comment by andrewcooke** [comment]
oh.  yeah, you've done something pretty weird.  tbh have no idea if that works well or not.

**Comment by andrewcooke** [comment]
i've had a long think about this and decided that the general design of simple-crypt isn't what you want for encrypting more data that will fit into memory.  i've described why at https://github.com/andrewcooke/simple-crypt#warnings

because of that i am not going to add this functionality to the package.

however, i do still worry about people writing smaller amounts of data to files.  as a step to helping those people i've added an example at https://github.com/andrewcooke/simple-crypt/blob/master/src/simplecrypt/example-file.py that shows what needs to be done.

**Pull request closed without merging**
